In [1]:
import numpy as np
import tensorflow as tf
import keras
from keras import layers

In [2]:
data = np.array(
    [
        [0.1, 0.2, 0.3],
        [0.8, 0.9, 1.0],
        [1.5, 1.6, 1.7],
    ]
)

In [3]:
layer = layers.Normalization()
layer.adapt(data)
normalized_data = layer(data)

In [4]:
normalized_data

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.2247449e+00, -1.2247449e+00, -1.2247448e+00],
       [ 0.0000000e+00, -1.0428640e-07,  0.0000000e+00],
       [ 1.2247449e+00,  1.2247448e+00,  1.2247449e+00]], dtype=float32)>

In [5]:
normalized_data.numpy().mean()

-1.3245477e-08

In [6]:
normalized_data.numpy().std()

1.0

In [7]:
data = [
    "ξεῖν᾽, ἦ τοι μὲν ὄνειροι ἀμήχανοι ἀκριτόμυθοι",
    "γίγνοντ᾽, οὐδέ τι πάντα τελείεται ἀνθρώποισι.",
    "δοιαὶ γάρ τε πύλαι ἀμενηνῶν εἰσὶν ὀνείρων:",
    "αἱ μὲν γὰρ κεράεσσι τετεύχαται, αἱ δ᾽ ἐλέφαντι:",
    "τῶν οἳ μέν κ᾽ ἔλθωσι διὰ πριστοῦ ἐλέφαντος,",
    "οἵ ῥ᾽ ἐλεφαίρονται, ἔπε᾽ ἀκράαντα φέροντες:",
    "οἱ δὲ διὰ ξεστῶν κεράων ἔλθωσι θύραζε,",
    "οἵ ῥ᾽ ἔτυμα κραίνουσι, βροτῶν ὅτε κέν τις ἴδηται.",
]

In [8]:
layer = layers.TextVectorization()
layer.adapt(data)
vectorized_text = layer(data)
vectorized_text

<tf.Tensor: shape=(8, 9), dtype=int64, numpy=
array([[37, 12, 25,  5,  9, 20, 21,  0,  0],
       [51, 34, 27, 33, 29, 18,  0,  0,  0],
       [49, 52, 30, 31, 19, 46, 10,  0,  0],
       [ 7,  5, 50, 43, 28,  7, 47, 17,  0],
       [24, 35, 39, 40,  3,  6, 32, 16,  0],
       [ 4,  2, 15, 14, 22, 23,  0,  0,  0],
       [36, 48,  6, 38, 42,  3, 45,  0,  0],
       [ 4,  2, 13, 41, 53,  8, 44, 26, 11]])>

In [9]:
vocab = ['a','b','c','d']
data = [['a','c','b'],['d','z','a']]
layer = layers.StringLookup(vocabulary=vocab)
vectorized_data=layer(data)
vectorized_data

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 3, 2],
       [4, 0, 1]])>