In [1]:
import tensorflow as tf
import keras
from keras import layers
import numpy as np

In [8]:
model = keras.models.Sequential()
model.add(layers.LSTM(128, input_shape =(100, 64)))

In [9]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 128)               98816     
                                                                 
Total params: 98816 (386.00 KB)
Trainable params: 98816 (386.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
input = np.random.random((32,100,64))

In [11]:
model(input)

<tf.Tensor: shape=(32, 128), dtype=float32, numpy=
array([[ 0.06830255,  0.33426037, -0.2280668 , ..., -0.11803098,
         0.05361152,  0.23165298],
       [ 0.08524558,  0.2685929 , -0.14083879, ..., -0.00583468,
         0.12351918,  0.29270893],
       [-0.09162324,  0.30375394, -0.24457046, ..., -0.11119272,
         0.08513726,  0.20812082],
       ...,
       [ 0.01620254,  0.25030524, -0.22140098, ..., -0.03011527,
         0.1208662 ,  0.14071275],
       [-0.00608991,  0.28867385, -0.18187392, ..., -0.12877892,
         0.03162476,  0.09065992],
       [ 0.08466666,  0.21175064, -0.17468305, ..., -0.14795563,
         0.23094252,  0.20041151]], dtype=float32)>

In [12]:
model.variables

[<tf.Variable 'lstm_1/lstm_cell/kernel:0' shape=(64, 512) dtype=float32, numpy=
 array([[ 0.0501997 , -0.08657222,  0.03320719, ..., -0.0862118 ,
         -0.04107983,  0.02334872],
        [-0.05951494, -0.03448389, -0.03241017, ...,  0.05525893,
         -0.08268989, -0.07983506],
        [ 0.06962168, -0.01874001, -0.03062432, ...,  0.04539706,
          0.02506983,  0.06950589],
        ...,
        [ 0.02382539,  0.01249871, -0.00884084, ...,  0.01113477,
          0.08461466, -0.05992257],
        [-0.04340509,  0.01731791, -0.08755868, ..., -0.0470756 ,
         -0.01319574,  0.09569493],
        [ 0.08750576,  0.02859159,  0.06332532, ..., -0.04731227,
          0.06169492, -0.03342612]], dtype=float32)>,
 <tf.Variable 'lstm_1/lstm_cell/recurrent_kernel:0' shape=(128, 512) dtype=float32, numpy=
 array([[ 0.03429818,  0.06551444,  0.01752037, ...,  0.01673148,
         -0.02052634, -0.00108883],
        [ 0.05924174, -0.01895237,  0.01748545, ...,  0.03938874,
         -0.004637

In [14]:
model = keras.Sequential()
model.add(layers.SimpleRNN(128, input_shape=(100,64) ))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 128)               24704     
                                                                 
Total params: 24704 (96.50 KB)
Trainable params: 24704 (96.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model(input)

<tf.Tensor: shape=(32, 128), dtype=float32, numpy=
array([[-0.13634752, -0.1723228 ,  0.11742685, ...,  0.91440445,
        -0.19778453,  0.67821723],
       [-0.32463434, -0.09139939, -0.6171858 , ...,  0.8733629 ,
         0.39810452,  0.77676964],
       [-0.66015965, -0.3971889 , -0.595516  , ...,  0.7218538 ,
         0.21412948,  0.42729637],
       ...,
       [-0.5982969 , -0.55361927,  0.17074777, ...,  0.84086114,
        -0.15404497,  0.89675176],
       [-0.42708582, -0.63677263, -0.0122096 , ...,  0.8617068 ,
        -0.32307187,  0.5016497 ],
       [-0.5306407 , -0.67347354, -0.3203308 , ...,  0.8917179 ,
        -0.37515047,  0.8447382 ]], dtype=float32)>

In [20]:
vocab_size=10000
num_features=64
model = keras.Sequential()
model.add(layers.Embedding(input_dim=vocab_size, output_dim=num_features))
model.add(layers.LSTM(128))
model.add(layers.Dense(10, activation='softmax'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 64)          640000    
                                                                 
 lstm_3 (LSTM)               (None, 128)               98816     
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 740106 (2.82 MB)
Trainable params: 740106 (2.82 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [32]:
input = np.random.randint(0,vocab_size,size=(32,100))
target = np.random.randint(0, 10, size=(32,1))
model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer=keras.optimizers.Adam(),
              metrics=[keras.metrics.SparseCategoricalAccuracy()])

In [33]:
history = model.fit(input, target, epochs=10, batch_size=8)

Epoch 1/10


/opt/homebrew/Caskroom/miniforge/base/envs/tf_env/lib/python3.10/site-packages/keras/src/backend.py:5727: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


4/4 [==============================] - 1s 26ms/step - loss: 2.3432 - sparse_categorical_accuracy: 0.1562
Epoch 2/10
4/4 [==============================] - 0s 26ms/step - loss: 2.2030 - sparse_categorical_accuracy: 0.1562
Epoch 3/10
4/4 [==============================] - 0s 25ms/step - loss: 2.0677 - sparse_categorical_accuracy: 0.2500
Epoch 4/10
4/4 [==============================] - 0s 25ms/step - loss: 1.8168 - sparse_categorical_accuracy: 0.2812
Epoch 5/10
4/4 [==============================] - 0s 26ms/step - loss: 1.6186 - sparse_categorical_accuracy: 0.3750
Epoch 6/10
4/4 [==============================] - 0s 25ms/step - loss: 1.4319 - sparse_categorical_accuracy: 0.5312
Epoch 7/10
4/4 [==============================] - 0s 26ms/step - loss: 1.2252 - sparse_categorical_accuracy: 0.5625
Epoch 8/10
4/4 [==============================] - 0s 25ms/step - loss: 1.2084 - sparse_categorical_accuracy: 0.5938
Epoch 9/10
4/4 [==============================] - 0s 26ms/step - loss: 1.1292 - spa

In [39]:
model.predict(input[:5])

1/1 [==============================] - 0s 21ms/step


array([[0.426146  , 0.03018093, 0.02969218, 0.01009038, 0.10628848,
        0.02841684, 0.0396408 , 0.03888062, 0.02584466, 0.26481918],
       [0.00912099, 0.00826434, 0.02755952, 0.09088288, 0.01258691,
        0.5829932 , 0.10902884, 0.00596579, 0.14499967, 0.0085978 ],
       [0.00885594, 0.00828758, 0.02717856, 0.10124345, 0.01259414,
        0.5653919 , 0.11125515, 0.00600195, 0.15069404, 0.00849725],
       [0.0231333 , 0.0136863 , 0.05298903, 0.04505505, 0.02000601,
        0.21251346, 0.43785143, 0.02199228, 0.15583849, 0.01693464],
       [0.49868354, 0.02645679, 0.02146885, 0.00722842, 0.10556715,
        0.01715779, 0.0254783 , 0.03576293, 0.01674952, 0.24544677]],
      dtype=float32)

In [40]:
target[:5]

array([[9],
       [5],
       [5],
       [6],
       [0]])

In [49]:
model = keras.Sequential()
model.add(layers.Embedding(10000,64))
model.add(layers.GRU(256, return_sequences=True,)) ##output shape - ( batch_size, time_steps, units)
model.add(layers.SimpleRNN(128))
model.add(layers.Dense(10, activation='softmax'))
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, None, 64)          640000    
                                                                 
 gru_2 (GRU)                 (None, None, 256)         247296    
                                                                 
 simple_rnn_4 (SimpleRNN)    (None, 128)               49280     
                                                                 
 dense_4 (Dense)             (None, 10)                1290      
                                                                 
Total params: 937866 (3.58 MB)
Trainable params: 937866 (3.58 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [50]:
input = np.random.randint(0,vocab_size,size=(32,100))
target = np.random.randint(0, 10, size=(32,1))
model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer=keras.optimizers.Adam(),
              metrics=[keras.metrics.SparseCategoricalAccuracy()])
history=model.fit(input, target, epochs=10, batch_size=32)

Epoch 1/10


/opt/homebrew/Caskroom/miniforge/base/envs/tf_env/lib/python3.10/site-packages/keras/src/backend.py:5727: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1/1 [==============================] - 1s 743ms/step - loss: 2.3104 - sparse_categorical_accuracy: 0.1250
Epoch 2/10
1/1 [==============================] - 0s 109ms/step - loss: 2.0612 - sparse_categorical_accuracy: 0.6562
Epoch 3/10
1/1 [==============================] - 0s 108ms/step - loss: 1.8169 - sparse_categorical_accuracy: 0.9375
Epoch 4/10
1/1 [==============================] - 0s 111ms/step - loss: 1.5074 - sparse_categorical_accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 114ms/step - loss: 1.3118 - sparse_categorical_accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 113ms/step - loss: 1.1230 - sparse_categorical_accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 115ms/step - loss: 0.9629 - sparse_categorical_accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 109ms/step - loss: 0.8282 - sparse_categorical_accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 109ms/step - loss: 0.7

In [51]:
model.predict(input[:5])

1/1 [==============================] - 0s 318ms/step


array([[0.05811029, 0.06183634, 0.05293751, 0.03395062, 0.0623646 ,
        0.03736534, 0.06058241, 0.07732039, 0.46648532, 0.08904713],
       [0.02409323, 0.6253244 , 0.01253859, 0.04375581, 0.02790624,
        0.09606948, 0.0613334 , 0.02158225, 0.03974992, 0.04764663],
       [0.02646111, 0.09750102, 0.03680229, 0.04000811, 0.02829788,
        0.61190736, 0.03430467, 0.06782592, 0.02366185, 0.03322979],
       [0.4451268 , 0.03922073, 0.05827165, 0.14204898, 0.07834244,
        0.03358084, 0.06313536, 0.02519507, 0.05843999, 0.05663809],
       [0.08248253, 0.06670571, 0.0382889 , 0.55697   , 0.04349488,
        0.04125578, 0.07215773, 0.01917469, 0.03093302, 0.04853668]],
      dtype=float32)

In [52]:
target[:5]

array([[8],
       [1],
       [5],
       [0],
       [3]])

In [65]:
model.layers[1].outbound_nodes

In [67]:
encoder_vocab=1000
decoder_vocab=2000

encoder_input = keras.Input(shape=(None,))
encoder_embed = layers.Embedding(input_dim=encoder_vocab, output_dim=64)(encoder_input)
output, state_h, state_c = layers.LSTM(64, return_state=True)(encoder_embed)
encoder_state=[state_h, state_c]
decoder_input = keras.Input(shape=(None,))
decoder_embed = layers.Embedding(input_dim=decoder_vocab, output_dim=64)(decoder_input)
decoder_output = layers.LSTM(64)(decoder_embed, initial_state=encoder_state)
output = layers.Dense(10, activation='softmax')(decoder_output)
model = keras.Model(inputs=[encoder_input, decoder_input], outputs=[output])
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_2 (InputLayer)        [(None, None)]               0         []                            
                                                                                                  
 input_3 (InputLayer)        [(None, None)]               0         []                            
                                                                                                  
 embedding_6 (Embedding)     (None, None, 64)             64000     ['input_2[0][0]']             
                                                                                                  
 embedding_7 (Embedding)     (None, None, 64)             128000    ['input_3[0][0]']             
                                                                                              

In [69]:
encoder_input = np.random.randint(0,encoder_vocab,size=(32,100))
decoder_input = np.random.randint(0,decoder_vocab,size=(32,100))
target = np.random.randint(0, 10, size=(32,1))
model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer=keras.optimizers.Adam(),
              metrics=[keras.metrics.SparseCategoricalAccuracy()])
history=model.fit((encoder_input, decoder_input), target, epochs=25, batch_size=32)

Epoch 1/25
1/1 [==============================] - 1s 901ms/step - loss: 2.3045 - sparse_categorical_accuracy: 0.0000e+00
Epoch 2/25
1/1 [==============================] - 0s 38ms/step - loss: 2.2917 - sparse_categorical_accuracy: 0.0625
Epoch 3/25
1/1 [==============================] - 0s 38ms/step - loss: 2.2790 - sparse_categorical_accuracy: 0.2812
Epoch 4/25
1/1 [==============================] - 0s 42ms/step - loss: 2.2663 - sparse_categorical_accuracy: 0.3125
Epoch 5/25
1/1 [==============================] - 0s 39ms/step - loss: 2.2530 - sparse_categorical_accuracy: 0.4062
Epoch 6/25
1/1 [==============================] - 0s 38ms/step - loss: 2.2389 - sparse_categorical_accuracy: 0.4062
Epoch 7/25
1/1 [==============================] - 0s 39ms/step - loss: 2.2237 - sparse_categorical_accuracy: 0.4062
Epoch 8/25
1/1 [==============================] - 0s 40ms/step - loss: 2.2067 - sparse_categorical_accuracy: 0.4375
Epoch 9/25
1/1 [==============================] - 0s 38ms/step - lo

In [70]:
model.predict((encoder_input[:5], decoder_input[:5]))

1/1 [==============================] - 0s 230ms/step


array([[0.09245473, 0.1453131 , 0.06451769, 0.09187844, 0.06408516,
        0.05804849, 0.17533341, 0.12742579, 0.10640304, 0.07454009],
       [0.1234583 , 0.43556708, 0.01215723, 0.02702597, 0.00242799,
        0.00371533, 0.05956478, 0.01719108, 0.31107312, 0.00781913],
       [0.0997817 , 0.13461304, 0.06324722, 0.10550001, 0.06195274,
        0.0573851 , 0.17583175, 0.12173584, 0.10663573, 0.07331688],
       [0.2938184 , 0.16216232, 0.01308621, 0.08232765, 0.00344548,
        0.00539551, 0.06195698, 0.01107697, 0.35757196, 0.00915852],
       [0.0999954 , 0.5248015 , 0.01026232, 0.02117701, 0.00191667,
        0.00287618, 0.05799011, 0.01725965, 0.2564667 , 0.00725437]],
      dtype=float32)

In [71]:
target[:5]

array([[6],
       [1],
       [6],
       [0],
       [1]])

In [82]:
model.layers[4].output

[<KerasTensor: shape=(None, 64) dtype=float32 (created by layer 'lstm_5')>,
 <KerasTensor: shape=(None, 64) dtype=float32 (created by layer 'lstm_5')>,
 <KerasTensor: shape=(None, 64) dtype=float32 (created by layer 'lstm_5')>]