In [9]:
import tensorflow as tf
import keras
from keras import layers

In [12]:
model = keras.Sequential([
    layers.Dense(3, activation='relu', name='layer1'),
    layers.Dense(4, activation='relu', name='layer2'),
    layers.Dense(2,  name='layer3')
])
x= tf.random.normal((4,3))
y = model(x)
y

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1.3399724 , 0.8667206 ],
       [0.7291853 , 0.47048196],
       [1.1279329 , 0.78167355],
       [0.5833016 , 1.0417581 ]], dtype=float32)>

In [13]:
layer1 = layers.Dense(3, activation='relu', name='layer1')
layer2 = layers.Dense(4, activation='relu', name='layer2')
layer3 = layers.Dense(2, name='layer3')
y = layer3(layer2(layer1(x)))
y

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.09227532,  0.08486008],
       [-0.01765659,  0.01623771],
       [-0.54909265,  0.5203797 ],
       [-1.3370439 ,  1.0331937 ]], dtype=float32)>

In [15]:
model = keras.Sequential()
model.add(layers.Dense(3, activation='relu', name='layer1'))
model.add(layers.Dense(4, activation='relu', name='layer2'))
model.add(layers.Dense(2,  name='layer3'))
y=model(x)
print(y)
model.summary()

tf.Tensor(
[[ 0.          0.        ]
 [ 0.          0.        ]
 [-0.28474823 -0.5721739 ]
 [-0.44008055 -1.5906756 ]], shape=(4, 2), dtype=float32)
Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (4, 3)                    12        
                                                                 
 layer2 (Dense)              (4, 4)                    16        
                                                                 
 layer3 (Dense)              (4, 2)                    10        
                                                                 
Total params: 38 (152.00 Byte)
Trainable params: 38 (152.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
x

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.9964266 ,  1.7605306 , -1.1461923 ],
       [-0.7166076 ,  1.076103  , -0.9184262 ],
       [ 1.5381393 ,  0.8297669 ,  0.8090582 ],
       [ 0.35487136, -0.3420166 ,  1.8957074 ]], dtype=float32)>

In [17]:
model.variables

[<tf.Variable 'layer1/kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[ 0.5470724 ,  0.9229412 , -0.7351365 ],
        [ 0.22072077, -0.9587922 , -0.88712144],
        [ 0.60672474,  0.2875986 ,  0.86910725]], dtype=float32)>,
 <tf.Variable 'layer1/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'layer2/kernel:0' shape=(3, 4) dtype=float32, numpy=
 array([[ 0.20941901, -0.27771795, -0.08847451,  0.31018972],
        [ 0.0633015 ,  0.59744   ,  0.19547737, -0.09824395],
        [-0.5741221 ,  0.77887344, -0.8526141 , -0.68441135]],
       dtype=float32)>,
 <tf.Variable 'layer2/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'layer3/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[-0.6816926 , -0.42840815],
        [-0.26174712, -0.9460876 ],
        [ 0.21971178,  0.19172573],
        [-0.03875017, -0.8636956 ]], dtype=float32)>,
 <tf.Variable 'layer3/bias:0' shape=(2,) dtype=float32, num

In [18]:
model=keras.Sequential()
model.add(layers.Input(shape=(4,3)))
model.add(layers.Dense(3, activation='relu', name='layer2'))
model.add(layers.Dense(2,  name='layer3'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer2 (Dense)              (None, 4, 3)              12        
                                                                 
 layer3 (Dense)              (None, 4, 2)              8         
                                                                 
Total params: 20 (80.00 Byte)
Trainable params: 20 (80.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.layers

In [20]:
model = keras.Sequential()
model.add(layers.Dense(2, activation="relu", input_shape=(4,)))

model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 10        
                                                                 
Total params: 10 (40.00 Byte)
Trainable params: 10 (40.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
